# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_register(object):
    def setupUi(self, Form_register):
        Form_register.setObjectName("Form_register")
        Form_register.resize(562, 500)
        self.label_captcha_pixmap = QtWidgets.QLabel(Form_register)
        self.label_captcha_pixmap.setGeometry(QtCore.QRect(300, 280, 191, 51))
        self.label_captcha_pixmap.setText("")
        self.label_captcha_pixmap.setAlignment(QtCore.Qt.AlignCenter)
        self.label_captcha_pixmap.setObjectName("label_captcha_pixmap")
        self.pushButton_refresh = QtWidgets.QPushButton(Form_register)
        self.pushButton_refresh.setGeometry(QtCore.QRect(60, 380, 79, 26))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.layoutWidget = QtWidgets.QWidget(Form_register)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 90, 431, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_password_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password_1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_1.setObjectName("lineEdit_password_1")
        self.gridLayout.addWidget(self.lineEdit_password_1, 1, 1, 1, 1)
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.gridLayout.addWidget(self.lineEdit_password_2, 2, 1, 1, 1)
        self.lineEdit_username = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.gridLayout.addWidget(self.lineEdit_username, 0, 1, 1, 1)
        self.StrongBodyLabel = StrongBodyLabel(self.layoutWidget)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.gridLayout.addWidget(self.StrongBodyLabel, 0, 0, 1, 1)
        self.StrongBodyLabel_2 = StrongBodyLabel(self.layoutWidget)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.gridLayout.addWidget(self.StrongBodyLabel_2, 1, 0, 1, 1)
        self.StrongBodyLabel_3 = StrongBodyLabel(self.layoutWidget)
        self.StrongBodyLabel_3.setObjectName("StrongBodyLabel_3")
        self.gridLayout.addWidget(self.StrongBodyLabel_3, 2, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Form_register)
        self.layoutWidget1.setGeometry(QtCore.QRect(60, 270, 231, 81))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StrongBodyLabel_4 = StrongBodyLabel(self.layoutWidget1)
        self.StrongBodyLabel_4.setObjectName("StrongBodyLabel_4")
        self.verticalLayout.addWidget(self.StrongBodyLabel_4)
        self.lineEdit_captcha = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_captcha.setObjectName("lineEdit_captcha")
        self.verticalLayout.addWidget(self.lineEdit_captcha)
        self.splitter = QtWidgets.QSplitter(Form_register)
        self.splitter.setGeometry(QtCore.QRect(330, 380, 161, 26))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.pushButton_register = QtWidgets.QPushButton(self.splitter)
        self.pushButton_register.setObjectName("pushButton_register")
        self.pushButton_cancel = QtWidgets.QPushButton(self.splitter)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.TitleLabel = TitleLabel(Form_register)
        self.TitleLabel.setGeometry(QtCore.QRect(170, 30, 211, 38))
        self.TitleLabel.setObjectName("TitleLabel")

        self.retranslateUi(Form_register)
        self.pushButton_cancel.clicked.connect(Form_register.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form_register)

    def retranslateUi(self, Form_register):
        _translate = QtCore.QCoreApplication.translate
        Form_register.setWindowTitle(_translate("Form_register", "注册"))
        self.pushButton_refresh.setText(_translate("Form_register", "刷新"))
        self.StrongBodyLabel.setText(_translate("Form_register", "用户名："))
        self.StrongBodyLabel_2.setText(_translate("Form_register", "密码："))
        self.StrongBodyLabel_3.setText(_translate("Form_register", "确认密码："))
        self.StrongBodyLabel_4.setText(_translate("Form_register", "验证码："))
        self.pushButton_register.setText(_translate("Form_register", "注册"))
        self.pushButton_cancel.setText(_translate("Form_register", "退出"))
        self.TitleLabel.setText(_translate("Form_register", "软件安全管家"))
from qfluentwidgets import StrongBodyLabel, TitleLabel
